### ISSUE TITLE
Question about code release and application.

### ISSUE THREAD

**Issue by Kim-GeonU** [VDIGPKU/DrivingGaussian#7]
I signed the application and got an e-mail from the author, which announces that the code is undergoing minor modifications.

And I haven't received following emails for a month.

I'm wondering whether the code modifications are still in progress or my application was just accidentally omitted..

**Comment by VDIGPKU** [comment]
Thank you for your interest. Download links have been sent for all current requests (due to cloud storage limitations, each link must be manually created and is valid for one download only). If you submitted a request but did not receive a link, it's likely that the email went to our spam folder. Please try resubmitting your request with a different email address. Your understanding is appreciated.
